name: Auto Builder CI

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * 0" # L3 image
  release:
    types:
      - released

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Enviroment Variables
        id: variables
        env:
          DOCKERHUB_USER: vcxpz
          DOCKERHUB_IMAGE: amp
          DOCKERIMAGE_TAG: alpine
        run: |
          echo "DOCKERHUB_IMAGE=${DOCKERHUB_IMAGE}" >>$GITHUB_ENV
          echo "DOCKERHUB_USER=${DOCKERHUB_USER}" >>$GITHUB_ENV
          echo "DOCKERIMAGE_TAG=${DOCKERIMAGE_TAG}" >>$GITHUB_ENV
          echo "::set-output name=VERSION::$(curl -sX GET "https://api.github.com/repos/hydazz/docker-${DOCKERHUB_IMAGE}/releases/latest" | jq -r .tag_name)"
          echo "::set-output name=USER_IMAGE::${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}"

      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${DOCKER_PASSWORD} | docker login -u ${DOCKERHUB_USER} --password-stdin

      - name: Github Login
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Build The Docker Image
        env:
          VERSION: ${{ steps.variables.outputs.VERSION }}
        run: |
          docker build --no-cache --pull . --file Dockerfile --build-arg VERSION="${VERSION}" --build-arg BUILD_DATE="$(date +%Y-%m-%d)" --tag ${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:cibuild

      - name: Test The Docker Image
        run: |
          set -x
          export RUN_ARGS="-e DEBUG=true -e TESTRUN=true"
          curl -sSL https://raw.githubusercontent.com/hydazz/scripts/main/docker/docker-ci.sh | bash

      - name: Get New Package Versions From Image
        run: |
          docker run --rm --entrypoint '/bin/sh' -v "$PWD":/tmp ${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:cibuild -c '\
            apk info -v | sort >/tmp/package_versions.txt'

      - name: Update README
        env:
          AMP_RELEASE: ${{ steps.variables.outputs.VERSION }}
        run: |
          chmod +x update_version_info.sh && ./update_version_info.sh

      - name: Commit And Push Changes To Github
        run: |
          git add -A
          git commit -m 'Bot Updating Files' || echo "No Changes"
          git push || echo "No Changes"

      - name: Tag And Push Docker Image
        env:
          VERSION: ${{ steps.variables.outputs.VERSION }}
        run: |
          docker tag ${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:cibuild ${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:${DOCKERIMAGE_TAG}
          docker tag ${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:cibuild ${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:alpine-${VERSION}
          docker push ${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:${DOCKERIMAGE_TAG}
          docker push ${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:alpine-${VERSION}
