name: Auto Builder CI

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * 0"
  release:
    types:
      - released

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: vcxpz
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Github Login
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Build And Push The Docker Image
        run: |
          docker build \
            --platform=linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --build-arg VERSION=$(curl -sX GET "https://api.github.com/repos/hydazz/docker-amp/releases/latest" | jq -r .tag_name) \
            --tag vcxpz/amp:latest \
            --tag vcxpz/amp:$(curl -sX GET "https://api.github.com/repos/hydazz/docker-amp/releases/latest" | jq -r .tag_name) \
            --file Dockerfile .

      - name: Get New Package Versions From Image
        run: |
          docker run --rm --entrypoint /bin/sh -v "$PWD":/tmp vcxpz/amp:latest -c "\
            apk info -v | sort >/tmp/package_versions.txt"

      - name: Update README
        run: |
          export APP_VERSION=$(curl -sX GET "https://api.github.com/repos/hydazz/docker-amp/releases/latest" | jq -r .tag_name)
          chmod +x update_version_info.sh && ./update_version_info.sh

      - name: Commit And Push Changes To Github
        run: |
          git add -A
          git commit -m "Bot Updating Files" || echo "No Changes"
          git push || echo "No Changes"

      - name: Sync README With Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: vcxpz
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vcxpz/amp
