name: Auto Builder CI

on:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * 0" # L3 image
  release:
    types:
      - released

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Set Enviroment Variables
        id: variables
        env:
          DOCKERHUB_USER: vcxpz
          DOCKERHUB_IMAGE: amp
          DOCKERIMAGE_TAG: latest
          PLATFORMS: linux/amd64,linux/arm64
        run: |
          echo "DOCKERHUB_IMAGE=${DOCKERHUB_IMAGE}" >>$GITHUB_ENV
          echo "DOCKERHUB_USER=${DOCKERHUB_USER}" >>$GITHUB_ENV
          echo "DOCKERIMAGE_TAG=${DOCKERIMAGE_TAG}" >>$GITHUB_ENV
          echo "::set-output name=AMP_RELEASE::$(curl -sX GET "https://api.github.com/repos/hydazz/docker-${DOCKERHUB_IMAGE}/releases/latest" | jq -r .tag_name)"
          echo "::set-output name=USER_IMAGE::${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}"
          echo "PLATFORMS=${PLATFORMS}" >>$GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: vcxpz
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Github Login
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Build And Push The Docker Image
        env:
          AMP_RELEASE: ${{ steps.variables.outputs.AMP_RELEASE }}
        run: |
          docker build \
            --platform=${PLATFORMS} \
            --output "type=image,push=true" \
            --build-arg AMP_RELEASE=${AMP_RELEASE} \
            --tag ${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:${DOCKERIMAGE_TAG} \
            --tag ${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:${AMP_RELEASE} \
            --file Dockerfile .

      - name: Get New Package Versions From Image
        run: |
          docker run --rm --entrypoint '/bin/sh' -v "$PWD":/tmp ${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:${DOCKERIMAGE_TAG} -c '\
            apk info -v | sort >/tmp/package_versions.txt'

      - name: Update README
        env:
          AMP_RELEASE: ${{ steps.variables.outputs.AMP_RELEASE }}
        run: |
          chmod +x update_version_info.sh && ./update_version_info.sh

      - name: Commit And Push Changes To Github
        run: |
          git add -A
          git commit -m 'Bot Updating Files' || echo "No Changes"
          git push || echo "No Changes"

      - name: Sync README With Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: vcxpz
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ steps.variables.outputs.USER_IMAGE }}
